# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6a5617bca12c3dbbd46fab6e9e939dd1d69b56e611300823b3fc0894541357b5f69c628b9c53f5b8a60185c8ff873edb9f0713483422f1c7b359d8ac3c6cf24

test:
  secret_key_base: 7b543a0f8ea1db7e8ec911d5027723efcab21a4d11a739126d0e1b07dff2f2308e21c0b74e6c7aa7f1458dfa33686302573a36032cf325f1aa70d8c715a05005

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
