# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c4c0e89936b3b04ac70c623ed621d06ccee812cd3168af8e132003ae93ec649b29b46e11ccc70ea7494e7a5fdb04d533de9ba995e20691bc5f952ab9788865b

test:
  secret_key_base: b3cd604e532e4f7453c19ed744ab428e03de37af169301051e6bad80add3153ce164c5a3077348259762fae62e230cd8c6ce9640f4d86f9c1a1f4a944f323ef7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
